apiVersion: v1
kind: Service
metadata:
  name: ml-api-service
spec:
  selector:
    app: ml-api
  ports:
  - name: rest-api
    port: 8000
    targetPort: 8000
  - name: grpc
    port: 50051
    targetPort: 50051
  type: LoadBalancer